
  describe('template spec', () => {
    it('Login válido', () => {
      cy.visit('https://the-internet.herokuapp.com/')
      cy.get(':nth-child(21) > a').click()
      cy.get('#username').type("tomsmith")
      cy.get('#password').type("SuperSecretPassword!")
      cy.get('.radius').click()
      cy.get('#flash').contains("You logged into a secure area!")
    })
    it('Login inválido 1', () => {
      cy.visit('https://the-internet.herokuapp.com/')
      cy.get(':nth-child(21) > a').click()
      cy.get('#username').type("Homsmith")
      cy.get('#password').type("SuperecretPassword!")
      cy.get('.radius').click()
      cy.get('#flash').contains("You logged into a secure area!")
    })
    it('Login inválido 2', () => {
      cy.visit('https://the-internet.herokuapp.com/')
      cy.get(':nth-child(21) > a').click()
      cy.get('#username').type("tomsmit")
      cy.get('#password').type("SuperSecretPassword!")
      cy.get('.radius').click()
      cy.get('#flash').contains("You logged into a secure area!")
    })
    it('Login inválido 3', () => {
      cy.visit('https://the-internet.herokuapp.com/')
      cy.get(':nth-child(21) > a').click()
      cy.get('#username').type("tomsmith")
      cy.get('#password').type("SuperSecretPassword")
      cy.get('.radius').click()
      cy.get('#flash').contains("You logged into a secure area!")
    })
    it('Login inválido 4', () => {
      cy.visit('https://the-internet.herokuapp.com/')
      cy.get(':nth-child(21) > a').click()
      cy.get('#username').type("")
      cy.get('#password').type("SuperSecretPassword!")
      cy.get('.radius').click()
      cy.get('#flash').contains("You logged into a secure area!")
    })
    it('Login inválido 5', () => {
      cy.visit('https://the-internet.herokuapp.com/')
      cy.get(':nth-child(21) > a').click()
      cy.get('#username').type("tomsmith")
      cy.get('#password').type("")
      cy.get('.radius').click()
      cy.get('#flash').contains("You logged into a secure area!")
    })
    it('Login inválido 6', () => {
      cy.visit('https://the-internet.herokuapp.com/')
      cy.get(':nth-child(21) > a').click()
      cy.get('#username').type("")
      cy.get('#password').type("")
      cy.get('.radius').click()
      cy.get('#flash').contains("You logged into a secure area!")
    })
  })